# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

development:
  adapter: postgresql
  encoding: unicode
  database: fastapi_example_development
  pool: 5
  username: fastapi_example
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: fastapi_example_test
  pool: 5
  username: fastapi_example
  password: password1
